# This is a basic workflow to help you get started with Actions

name: Azure Function Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Main ]
env:
  AZURE_FUNCTIONAPP_NAME: poq-fa-sandbox  # set this to your function app name on Azure
  POM_XML_DIRECTORY: /POQPost                       # set this to the directory which contains pom.xml file
  POM_FUNCTIONAPP_NAME: poq-fa-sandbox   # set this to the function app name in your local development environment
  JAVA_VERSION: '11'                      # set this to the java version to use  
  
jobs:
  # This workflow contains a single job called "build"
  deoloy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Restore Project Dependencies Using Mvn'
      shell: pwsh
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
     
         
             

            
            
        
