# This is a basic workflow to help you get started with Actions

name: AzureARMDeploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
jobs:
  # This workflow contains a single job called "build"
  deoloy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Azure ARM Deployment
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name SADeployment \
            --resource-group cloud-shell-storage-centralindia \
            --template-file armtemplate\StorageAccount.json \
            --parameters armtemplate\StorageAccount.params.json \
             

            
            
        
