name: sandbox

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: sandbox
    environment: sandbox
    steps:
    - uses: actions/checkout@v2

    - name: Cache dependency database
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
            
    - name: Package functions
      run: mvn clean package

    - name: Deploy Azure functions
      uses: Azure/functions-action@v1
      with:
        app-name: hello-${{ github.event.repository.name }}-${{ env.ENVIRONMENT }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'target/azure-functions/hello'
